---
- hosts: kubernetes-*
  tasks:
  - name: transfer data from ansible-master-nodes to kubernetes-master-nodes
    copy:
      src: /home/ansible/download/
      dest: /home/ansible/download/

- hosts: kubernetes-*
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: test
    command: pwd
    register: pwd_result # register指令把pwd执行结果寄存到自定义变量中
  - name: echo pwd
    debug:
      msg: "{{pwd_result}}"  # 打印变量

  - name: install yum on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm --import /etc/pki/rpm-gpg/RPM*
      rpm -ivh yum-3.4.3-167.el7.centos.noarch.rpm --force --nodeps 
    register: output1   

  - name: output of install yum on nodes
    debug: 
      msg: "{{ output1 }}" 
      
  - name: install yum-langpacks on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm -ivh yum-langpacks-0.4.2-7.el7.noarch.rpm
    register: output2 
  - name: output of install yum-langpacks on nodes
    debug: 
      msg: "{{ output2 }}"  
  
  - name: install yum-metadata on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm -ivh yum-metadata-parser-1.1.4-10.el7.x86_64.rpm
    register: output3 
  - name: output of install yum-metadata on nodes
    debug: 
      msg: "{{ output3 }}" 	
  
  - name: install yum-plugin on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm -ivh yum-plugin-fastestmirror-1.1.31-53.el7.noarch.rpm
    register: output4 
  - name: output of install yum-plugin on nodes
    debug: 
      msg: "{{ output4 }}" 
    
  - name: install yum-utils on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm -ivh yum-utils-1.1.31-53.el7.noarch.rpm
    register: output5 
  - name: output of install yum-utils on nodes
    debug: 
      msg: "{{ output5 }}" 
  
  - name: install PackageKit-yum on nodes
    shell: |
      cd /home/ansible/download/ 
      rpm -ivh PackageKit-yum-plugin-1.1.10-2.el7.centos.x86_64.rpm
    register: output6 
  - name: output of install PackageKit-yum on nodes
    debug: 
      msg: "{{ output6 }}"    

      
      