---
- hosts: kubernetes-*
  tasks:
  - name: transfer data from ansible-master-nodes to kubernetes-master-nodes
    copy:
      src: /home/ansible/download/
      dest: /home/ansible/download/

- hosts: kubernetes-*
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: install yum on nodes
    command: cd /home/ansible/download/ && rpm -ivh PackageKit-yum-plugin-1.1.10-2.el7.centos.x86_64.rpm && rpm -ivh yum-langpacks-0.4.2-7.el7.noarch.rpm && rpm -ivh yum-3.4.3-167.el7.centos.noarch.rpm && rpm -ivh yum-metadata-parser-1.1.4-10.el7.x86_64.rpm && rpm -ivh yum-plugin-fastestmirror-1.1.31-53.el7.noarch.rpm && rpm -ivh yum-utils-1.1.31-53.el7.noarch.rpm      
    register: output

  - name: output of install yum on nodes
    debug: 
      msg: "{{ output }}"