---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: install yum on nodes
    shell:
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/PackageKit-yum-plugin-1.1.10-2.el7.centos.x86_64.rpm
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-langpacks-0.4.2-7.el7.noarch.rpm
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-3.4.3-167.el7.centos.noarch.rpm
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-metadata-parser-1.1.4-10.el7.x86_64.rpm
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-plugin-fastestmirror-1.1.31-53.el7.noarch.rpm
      cmd: wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-utils-1.1.31-53.el7.noarch.rpm
      cmd: rpm -ivh PackageKit-yum-plugin-1.1.10-2.el7.centos.x86_64.rpm
      cmd: rpm -ivh yum-langpacks-0.4.2-7.el7.noarch.rpm
      cmd: rpm -ivh yum-3.4.3-167.el7.centos.noarch.rpm
      cmd: rpm -ivh yum-metadata-parser-1.1.4-10.el7.x86_64.rpm
      cmd: rpm -ivh yum-plugin-fastestmirror-1.1.31-53.el7.noarch.rpm
      cmd: rpm -ivh yum-utils-1.1.31-53.el7.noarch.rpm
